# Generated by Django 2.0.4 on 2018-05-06 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meallogger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='calories',
            new_name='ounces',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meal',
            name='mealtime',
            field=models.CharField(choices=[('BF', 'Breakfast'), ('BR', 'Brunch'), ('LU', 'Lunch'), ('SNK', 'Snack'), ('DIN', 'Dinner'), ('LSNK', 'Late Snack')], default='Breakfast', max_length=60),
        ),
    ]
