# Generated by Django 2.0.4 on 2018-05-09 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meallogger', '0004_auto_20180507_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='items',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='ounces',
        ),
        migrations.AddField(
            model_name='meal',
            name='item',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='meal',
            name='measure',
            field=models.CharField(choices=[('ounces', 'oz'), ('grams', 'g'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='oz', max_length=8),
        ),
        migrations.AddField(
            model_name='meal',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='mealtime',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('brunch', 'Brunch'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner'), ('late snack', 'Late Snack')], default='Breakfast', max_length=12),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
