# Generated by Django 2.0.4 on 2018-05-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meallogger', '0005_auto_20180508_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='measure',
        ),
        migrations.AddField(
            model_name='meal',
            name='unit',
            field=models.CharField(choices=[('ounces', 'oz'), ('grams', 'g'), ('small', 'small'), ('medium', 'medium'), ('large', 'large')], default='oz', max_length=8),
        ),
    ]
