# Generated by Django 2.0.4 on 2018-05-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meallogger', '0006_auto_20180509_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='name',
            new_name='username',
        ),
    ]
