# Generated by Django 2.0.4 on 2018-05-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meallogger', '0007_auto_20180512_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
